language: php

php:
  - 5.5
  - 5.6
  - 7.0

install: composer require --no-update symfony/http-foundation $SYMFONY_VERSION; composer install

script: vendor/bin/phpunit

env:
  - SYMFONY_VERSION: ~2.8.0
  - SYMFONY_VERSION: ~3.0.0
