language: php

matrix:
  include:
  - php: 5.6
    env: SYMFONY_VERSION=2
  - php: 5.6
    env: SYMFONY_VERSION=3
  - php: 7.0
    env: SYMFONY_VERSION=2
  - php: 7.0
    env: SYMFONY_VERSION=3
  - php: 7.1
    env: SYMFONY_VERSION=2
  - php: 7.1
    env: SYMFONY_VERSION=3
  - php: 7.1
    env: SYMFONY_VERSION=4
  - php: 7.2
    env: SYMFONY_VERSION=2
  - php: 7.2
    env: SYMFONY_VERSION=3
  - php: 7.2
    env: SYMFONY_VERSION=4
  - php: 7.3
    env: SYMFONY_VERSION=2
  - php: 7.3
    env: SYMFONY_VERSION=3
  - php: 7.3
    env: SYMFONY_VERSION=4

install:
  - if [ ! -z "$SYMFONY_VERSION" ]; then composer require --no-update symfony/http-foundation \~$SYMFONY_VERSION; fi
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix -v --dry-run

cache:
  directories:
    - $HOME/.composer/cache/files
