language: php

php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"

install:
  - if [ "$SYMFONY_VERSION" != "none" ]; then composer require --no-update symfony/http-foundation \~$SYMFONY_VERSION; fi
  - composer install

script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix -v --dry-run

env:
  - SYMFONY_VERSION: none
  - SYMFONY_VERSION: 2
  - SYMFONY_VERSION: 3
  - SYMFONY_VERSION: 4

matrix:
  exclude:
  - php: 5.6
    env: SYMFONY_VERSION=4
  - php: 7.0
    env: SYMFONY_VERSION=4

cache:
  directories:
    - $HOME/.composer/cache/files
